const products = {
    watches: [
        {
            article_number: 29374,
            brand: "casio",
            model: "edifice",
            model_info: "EQB-1200D-2AER SOLAR BLUETOOTH",
            price: 275,
            case_diameter: 45.6,
            bracelet_material: "stainless steel",
            case_material: ["stainless steel"],
            dial_color: "blue",
            mechanism: "analog",
        },
        {
            article_number: 29375,
            brand: "casio",
            model: "edifice",
            model_info: "EFS-S620BL-1AVUEF SOLAR CHRONOGRAPH",
            price: 183,
            case_diameter: 45.5,
            bracelet_material: "leather",
            case_material: ["stainless steel"],
            dial_color: "black",
            mechanism: "analog",
        },
        {
            article_number: 29376,
            brand: "casio",
            model: "g-shock",
            model_info: "GST-B100GB-1A9ER WAVE CEPTOR SOLAR BLUETOOTH",
            price: 395,
            case_diameter: 53.8,
            bracelet_material: "resin",
            case_material: ["stainless steel", "resin"],
            dial_color: "black",
            mechanism: "analog",
        },
        {
            article_number: 29377,
            brand: "casio",
            model: "g-shock",
            model_info: "GA-2000BT-1AER BHUTAN TEXTILE LIMITED EDITION",
            price: 173,
            case_diameter: 51.2,
            bracelet_material: "resin",
            case_material: ["stainless steel"],
            dial_color: "black",
            mechanism: "analog",
        },
        {
            article_number: 29378,
            brand: "casio",
            model: "g-shock",
            model_info: "GW-9400-1ER RANGEMAN",
            price: 300,
            case_diameter: 53,
            bracelet_material: "resin",
            case_material: ["resin"],
            dial_color: "",
            mechanism: "digital",
        },
        {
            article_number: 29379,
            brand: "seiko",
            model: "5 sport",
            model_info: "SRPJ47K1",
            price: 303,
            case_diameter: 43,
            bracelet_material: "stainless steel",
            case_material: ["stainless steel"],
            dial_color: "brown",
            mechanism: "analog",
        },
        {
            article_number: 29380,
            brand: "seiko",
            model: "presage",
            model_info: "SRPB41J1",
            price: 420,
            case_diameter: 40.5,
            bracelet_material: "stainless steel",
            case_material: ["stainless steel"],
            dial_color: "blue",
            mechanism: "analog",
        },
        {
            article_number: 29381,
            brand: "orient",
            model: "sports",
            model_info: "RA-AA0814R",
            price: 400,
            case_diameter: 42,
            bracelet_material: "stainless steel",
            case_material: ["stainless steel"],
            dial_color: "red",
            mechanism: "analog",
        },
        {
            article_number: 29382,
            brand: "orient",
            model: "bambino",
            model_info: "FAC08002F",
            price: 247,
            case_diameter: 42,
            bracelet_material: "leather",
            case_material: ["stainless steel"],
            dial_color: "green",
            mechanism: "analog",
        },
        {
            article_number: 29383,
            brand: "orient",
            model: "bambino",
            model_info: "FAC08001T",
            price: 291,
            case_diameter: 42,
            bracelet_material: "leather",
            case_material: ["stainless steel", "gold coating"],
            dial_color: "brown",
            mechanism: "analog",
        },
        {
            article_number: 29384,
            brand: "orient",
            model: "mako",
            model_info: "RA-AA0008B",
            price: 330,
            case_diameter: 42,
            bracelet_material: "stainless steel",
            case_material: ["stainless steel"],
            dial_color: "black",
            mechanism: "analog",
        },
        {
            article_number: 29385,
            brand: "citizen",
            model: "eco-drive",
            model_info: "RA-AA0008B",
            price: 330,
            case_diameter: 44.8,
            bracelet_material: "stainless steel",
            case_material: ["stainless steel"],
            dial_color: "blue",
            mechanism: "analog",
        },
    ],
}

export default products
