const products = {
    watches: [
        {
            article_number: 29374,
            brand: "casio",
            model: "edifice",
            model_info: "EQB-1200D-2AER SOLAR BLUETOOTH",
            price: 275,
            case_diameter: 45.6,
            band_material: "stainless_steel",
            case_material: ["stainless_steel"],
            dial_color: "blue",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29375,
            brand: "casio",
            model: "edifice",
            model_info: "EFS-S620BL-1AVUEF SOLAR CHRONOGRAPH",
            price: 183,
            case_diameter: 45.5,
            band_material: "leather",
            case_material: ["stainless_steel"],
            dial_color: "black",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29376,
            brand: "casio",
            model: "g-shock",
            model_info: "GST-B100GB-1A9ER WAVE CEPTOR SOLAR BLUETOOTH",
            price: 395,
            case_diameter: 53.8,
            band_material: "resin",
            case_material: ["stainless_steel", "resin"],
            dial_color: "black",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29377,
            brand: "casio",
            model: "g-shock",
            model_info: "GA-2000BT-1AER BHUTAN TEXTILE LIMITED EDITION",
            price: 173,
            case_diameter: 51.2,
            band_material: "resin",
            case_material: ["stainless_steel"],
            dial_color: "black",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29378,
            brand: "casio",
            model: "g-shock",
            model_info: "GW-9400-1ER RANGEMAN",
            price: 300,
            case_diameter: 53,
            band_material: "resin",
            case_material: ["resin"],
            dial_color: "",
            mechanism: "digital",
            reviews: [],
        },
        {
            article_number: 29379,
            brand: "seiko",
            model: "5 sport",
            model_info: "SRPJ47K1",
            price: 303,
            case_diameter: 43,
            band_material: "stainless_steel",
            case_material: ["stainless_steel"],
            dial_color: "brown",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29380,
            brand: "seiko",
            model: "presage",
            model_info: "SRPB41J1",
            price: 420,
            case_diameter: 40.5,
            band_material: "stainless_steel",
            case_material: ["stainless_steel"],
            dial_color: "blue",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29381,
            brand: "orient",
            model: "sports",
            model_info: "RA-AA0814R",
            price: 400,
            case_diameter: 42,
            band_material: "stainless_steel",
            case_material: ["stainless_steel"],
            dial_color: "red",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29382,
            brand: "orient",
            model: "bambino",
            model_info: "FAC08002F",
            price: 247,
            case_diameter: 42,
            band_material: "leather",
            case_material: ["stainless_steel"],
            dial_color: "green",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29383,
            brand: "orient",
            model: "bambino",
            model_info: "FAC08001T",
            price: 291,
            case_diameter: 42,
            band_material: "leather",
            case_material: ["stainless_steel", "gold_coating"],
            dial_color: "brown",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29384,
            brand: "orient",
            model: "mako",
            model_info: "RA-AA0008B",
            price: 330,
            case_diameter: 42,
            band_material: "stainless_steel",
            case_material: ["stainless_steel"],
            dial_color: "black",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29385,
            brand: "citizen",
            model: "eco-drive",
            model_info: "RA-AA0008B",
            price: 330,
            case_diameter: 44.8,
            band_material: "stainless_steel",
            case_material: ["stainless_steel"],
            dial_color: "blue",
            mechanism: "analog",
            reviews: [],
        },
        // new
        {
            article_number: 29386,
            brand: "casio",
            model: "g-shock",
            model_info: "GST-B100-1AER WAVE CEPTOR SOLAR BLUETOOTH",
            price: 304,
            case_diameter: 53.8,
            band_material: "stainless_steel",
            case_material: ["polymer"],
            dial_color: "black",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29387,
            brand: "casio",
            model: "g-shock",
            model_info: "GA-2200SKL-4AER",
            price: 115,
            case_diameter: 47.1,
            band_material: "polymer",
            case_material: ["polymer"],
            dial_color: "black",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29388,
            brand: "casio",
            model: "g-shock",
            model_info: "GST-B400D-1AER SOLAR BLUETOOTH",
            price: 360,
            case_diameter: 49.6,
            band_material: "stainless_steel",
            case_material: ["stainless_steel"],
            dial_color: "black",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29385,
            brand: "casio",
            model: "edifice",
            model_info: "EFV-C110D-2AVEF",
            price: 90,
            case_diameter: 51.3,
            band_material: "stainless_steel",
            case_material: ["stainless_steel"],
            dial_color: "blue",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29389,
            brand: "orient",
            model: "bambino",
            model_info: "FAC08004D",
            price: 270,
            case_diameter: 42,
            band_material: "leather",
            case_material: ["stainless_steel"],
            dial_color: "blue",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29390,
            brand: "orient",
            model: "sk",
            model_info: "RA-AA0B03I",
            price: 380,
            case_diameter: 40,
            band_material: "stainless_steel",
            case_material: ["stainless_steel"],
            dial_color: "blue",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29391,
            brand: "orient",
            model: "bambino",
            model_info: "FAC00007W",
            price: 280,
            case_diameter: 42,
            band_material: "leather",
            case_material: ["stainless_steel", "gold_coating"],
            dial_color: "white",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29392,
            brand: "orient",
            model: "contemporary",
            model_info: "RA-BA0006B",
            price: 260,
            case_diameter: 44,
            band_material: "leather",
            case_material: ["stainless_steel"],
            dial_color: "black",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29393,
            brand: "seiko",
            model: "sport",
            model_info: "SSB421P1",
            price: 315,
            case_diameter: 40,
            band_material: "textile",
            case_material: ["stainless_steel"],
            dial_color: "black",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29394,
            brand: "seiko",
            model: "prospex",
            model_info: "SNE593P1",
            price: 500,
            case_diameter: 43,
            band_material: "polymer",
            case_material: ["stainless_steel"],
            dial_color: "blue",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29395,
            brand: "citizen",
            model: "eco-drive",
            model_info: "CA7022-87E",
            price: 240,
            case_diameter: 43,
            band_material: "stainless_steel",
            case_material: ["stainless_steel"],
            dial_color: "black",
            mechanism: "analog",
            reviews: [],
        },
        {
            article_number: 29396,
            brand: "citizen",
            model: "super-titanium",
            model_info: "CA4570-88L",
            price: 360,
            case_diameter: 44,
            band_material: "stainless_steel",
            case_material: ["stainless_steel"],
            dial_color: "blue",
            mechanism: "analog",
            reviews: [],
        },
    ],
}

export default products
