export const initialProduct = {
    _id: "",
    nameId: "",
    article_number: "",
    fullName: "",
    brand: "",
    model: "",
    model_info: "",
    price: 0,
    case_diameter: 0,
    bracelet_material: "",
    case_material: [],
    image_urls: [],
    dial_color: "",
    mechanism: "",
    createdAt: "",
    updatedAt: "",
    __v: 0,
}
